version: '3.7'

services:
  database:
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=test_integration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis_tmp
    restart: unless-stopped
    expose:
      - 6379
    command: redis-server --protected-mode no
